CREATE TABLE IF NOT EXISTS buecher (
  id VARCHAR(32) PRIMARY KEY,
  buch_titel VARCHAR(250) NOT NULL,
  author VARCHAR(250) DEFAULT NULL,
  genre VARCHAR(250) DEFAULT NULL,
  inhalt VARCHAR(250) DEFAULT NULL,
  notiz VARCHAR(250) DEFAULT NULL
);